# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'registry'
  - name: 'imageName'
    value: 'exercise:$(build.buildId)'

steps:
  - script: docker build -f Dockerfile -t $(registry)/$(registryId)/$(imageName) .
    displayName: 'docker build'
  - script: |
      docker login $(registry) -u $(registryId) -p $(registryPassword)
      docker push $(registry)/$(registryId)/$(imageName)
    displayName: 'docker push'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: ks/**
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
  - task: HelmDeploy@0
    displayName: 'helm upgrade'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: digitalocean
      namespace: dev
      command: upgrade
      chartType: FilePath
      chartPath: '$(System.DefaultWorkingDirectory)/gokadin.exercise/drop/ks'
      releaseName: exercise
      overrideValues: 'image.tag=$(Build.BuildId)'