apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: exercise
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
        - name: exercise
          image: repo.treescale.com/godikadze/exercise:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 17000
          resources:
            requests:
              cpu: 150m
            limits:
              cpu: 300m
      imagePullSecrets:
        - name: treescale-auth

---

apiVersion: v1
kind: Service
metadata:
  name: exercise
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 17000
  selector:
    app: exercise
