version: '3.1'

services:
  exercise:
    image: exercise
    container_name: exercise
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
    - APP_ENV=development
    ports:
    - 17000:17000
    volumes:
    - ./:/app
    depends_on:
    - exercise-mongo

  exercise-mongo:
    image: mongo
    container_name: exercise-mongo
    ports:
    - 27017:27017
